# --- DECORACIÓN ---
decoration {
    rounding = 5
    rounding_power = 3
    active_opacity = 1

    blur {
        enabled = true
        size = 8          # 6–12 suele quedar bien (más grande = más borroso)
        passes = 3        # 2–4, más pases = más calidad y más GPU (3 es buen balance)
        ignore_opacity = true    # muy importante para que el blur respete opacidades <1
        new_optimizations = true # casi siempre sí
        xray = true             # prueba true si quieres un look más "profundo"
        vibrancy = 0.2           # sutil saturación (0.1–0.4), da más feeling "mac"
        vibrancy_darkness = 0.0
    }

    shadow {
        enabled = true

        # Tamaño de la sombra (en pixeles)
        range = 15

        # Qué tan rápido se desvanece la sombra (1 = suave/lineal, 4 = abrupto/concentrado)
        render_power = 3


        # Color de la sombra INACTIVA (Transparente = Sin sombra visual)
        color_inactive = rgba(00000000)

        # Evita renderizar sombra DETRÁS de la ventana (ahorra recursos y evita glitches en transparencias)
        ignore_window = true

    }
}

group {
    # --- comportamiento ---
    auto_group = true
    insert_after_current = true
    drag_into_group = 1
    merge_groups_on_drag = true
    merge_groups_on_groupbar = true
    group_on_movetoworkspace = false



    groupbar {
        enabled = true

        # --- texto ---
        render_titles = true
        font_family = DankMono Nerd Font
        font_size = 13
        font_weight_active = bold
        font_weight_inactive = normal

        text_color = 0xffffffff
        text_color_inactive = 0xffaaaaaa
        text_color_locked_active = 0xff000000

        # --- tamaño ---
        height = 15
        indicator_height = 6
        indicator_gap = 0
        text_padding = 0
        indicator_height = 0
        # --- forma ---
        rounding = 6
        rounding_power = 2.5
        round_only_edges = true

        # --- espaciado ---
        keep_upper_gap = false

        # --- efectos ---
        gradients = true
        blur = false
        scrolling = true


    }
}


