# --- DECORACIÓN ---
decoration {
    rounding = 10
    rounding_power = 2
    active_opacity = 1

    blur {
        enabled = true
        size = 6
        passes = 2
        ignore_opacity = true
        new_optimizations = false
        xray = false
        vibrancy = 0.2
        contrast = 1.0
        brightness = 1.0

    }

    shadow {
        enabled = true
        range = 8
        render_power = 2
        color_inactive = rgba(00000000)
         ignore_window = true

    }
}

group {
    # --- comportamiento ---
    auto_group = true
    insert_after_current = true
    drag_into_group = 1
    merge_groups_on_drag = true
    merge_groups_on_groupbar = true
    group_on_movetoworkspace = false



    groupbar {
        enabled = true

        # --- texto ---
        render_titles = true
        font_family = DankMono Nerd Font
        font_size = 13
        font_weight_active = bold
        font_weight_inactive = normal

        text_color = 0xffffffff
        text_color_inactive = 0xffaaaaaa
        text_color_locked_active = 0xff000000

        # --- tamaño ---
        height = 15
        indicator_height = 6
        indicator_gap = 0
        text_padding = 0
        indicator_height = 0
        # --- forma ---
        rounding = 6
        rounding_power = 2.5
        round_only_edges = true

        # --- espaciado ---
        keep_upper_gap = false

        # --- efectos ---
        gradients = true
        blur = false
        scrolling = true


    }
}


