# --- CONFIGURACIÓN GENERAL ---
general {
    gaps_in = 5
    gaps_out =10
    border_size = 3

    # Layout activo (opciones: master, dwindle, scrolling)
    layout = scrolling

    # Tearing
    allow_tearing = false
}
