# Configuración de hyprpaper
# Preload de imágenes para cambio instantáneo

# Ruta a tus imágenes de fondo (ajusta la ruta según tu sistema)
preload = /home/diego/Imágenes/ichigo.jpg
preload = /home/diego/Imágenes/WallpapersVertical/1008360.png

# Configura el fondo para cada monitor
# wallpaper = nombre_del_monitor,ruta_a_la_imagen

# Configura fondos específicos para cada monitor
wallpaper = HDMI-A-1,/home/diego/Imágenes/WallpapersVertical/1008360.png
wallpaper = DP-1,/home/diego/Imágenes/ichigo.jpg

# Opciones adicionales:
splash = false  # Deshabilita la pantalla de inicio de Hyprland

# Escala de imágenes (opcional, puedes probar diferentes valores)
scale = fit  # Opciones: fit, crop, stretch, fill, center
