# Hyprland Main Configuration File
# Modularized by Antigravity

# --- Sourcing Modules ---
source = ./monitors.conf
source = ./workspaces.conf
source = ./env.conf
source = ./general.conf
source = ./animations.conf
source = ./input.conf
source = ./layouts/dwindle.conf
source = ./layouts/master.conf
source = ./layouts/scrolling.conf
source = ./misc.conf
source = ./keybinds/keybinds_scrolling.conf
source = ./windowrules.conf
source = ./layerrules.conf
source = ./autostart.conf
source = ./plugins.conf
source = ./decoration.conf
source = ./colors/static-colors.conf

