# --- INPUT ---
input {
    kb_layout = us
    kb_variant = altgr-intl
    #kb_options = grp:alt_shift_toggle
    follow_mouse = 1

    kb_options = caps:super, shift:both_capslock

    # Repetición de teclas (hacerlo mas rápido)
    repeat_rate = 50
    repeat_delay = 300

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    numlock_by_default = true
}

# Configuración del Cursor
cursor {

    no_warps = false
    warp_on_change_workspace = 2

    no_hardware_cursors = true # Reemplazo moderno para WLR_NO_HARDWARE_CURSORS
}

