# --- REGLAS DE VENTANAS (Window Rules) ---
# Vea https://wiki.hyprland.org/Configuring/Window-Rules/
# Nota: windowrulev2 esta deprecado en favor de la sintaxis unificada de windowrule

# Sintaxis (Unified): windowrule = RULE, MATCHERS
# Matchers comunes: class:^(regex)$, title:^(regex)$, xwayland:1, floating:1, etc.
# Sidebar Pyprland: la geometria la controla Pyprland (size/position).

# Steam: Siempre flotante
windowrule =workspace 1, float on, match:class ^(steam)$


windowrule = float on, size 284 552 , match:class ^(org.kde.kalk)$

# Dota 2: Workspace 1, Fullscreen
windowrule = workspace 1, fullscreen on, match:class ^(dota2)$

# XWayland Video Bridge (Fix para compartir pantalla)
# Hace la ventana invisible y pequeña para que no estorbe pero funcione

# Zoom: Flotante y corrección de foco
windowrule = float on, match:class ^(zoom)$


# Swappy: Editor de capturas flotante y centrado
windowrule = float on, match:class ^(swappy)$
windowrule = float on, match:class ^(com.gabm.satty)$

# Flotante: Ark de KDE
windowrule = float on, size 830 600, match:class ^(org.kde.ark)$
# YouTube Music: Workspace 5
windowrule = workspace 4, match:class ^(com.github.th_ch.youtube_music)$

# Flotante: whatsApp Desktop
windowrule = float on, size 800 600, match:class ^(elecwhat)$
#VENTANAS DE QUICKSHELL
windowrule = float on, rounding 25, match:class ^(org.quickshell)$

# Vesktop: Workspace 6

# Free Download Manager: Flotante
windowrule = float on, match:class ^(fdm)$


windowrule = float on, size 800 500, match:class ^(xdg-desktop-portal-gtk)$


windowrule {
  name = vscode_starting_width
  match:class = code
  scrolling_width = 1.0
}

windowrule {
  name = vscode_insiders_starting_width
  match:class = code-insiders
  scrolling_width = 1.0
}

windowrule {
  name = helium_starting_width
  match:class = helium
  scrolling_width = 1.0
}

windowrule {
  name = google_antigravity_starting_width
  match:class = antigravity
  scrolling_width = 1.0
}
