# --- CONFIGURACIÓN DE WORKSPACES ---

# Monitor Principal (DP-1): Workspaces 1-3
workspace = 1, monitor:DP-1,persistent:true
workspace = 2, monitor:DP-1,persistent:true


# Monitor Secundario (HDMI-A-1): Workspaces 4-6 con master horizontal
workspace = 3, monitor:HDMI-A-1, persistent:true, layout:master, layoutopt:orientation:top
workspace = 4, monitor:HDMI-A-1, persistent:true, layout:master, layoutopt:orientation:top
