# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║                      ATAJOS DE TECLADO - LAYOUT MASTER                       ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

$scripts = ~/.config/hypr/scripts
$scripts_layout = $scripts/layout

# ┌──────────────────────────────────────────────────────────────────────────────┐
# │ Intercambiar Ventanas                                                        │
# └──────────────────────────────────────────────────────────────────────────────┘

bind = SUPER SHIFT, left,  exec, $scripts_layout/smart-swap.sh l
bind = SUPER SHIFT, right, exec, $scripts_layout/smart-swap.sh r
bind = SUPER SHIFT, up,    exec, $scripts_layout/smart-swap.sh u
bind = SUPER SHIFT, down,  exec, $scripts_layout/smart-swap.sh d

# Foco a la izquierda
bind = SUPER, left, movefocus, l

# Foco a la derecha
bind = SUPER, right, movefocus, r



# ┌──────────────────────────────────────────────────────────────────────────────┐
# │ Mover Ventana a Workspace                                                    │
# └──────────────────────────────────────────────────────────────────────────────┘
bind = SUPER, F1, movetoworkspace, 1
bind = SUPER, F2, movetoworkspace, 2
bind = SUPER, F3, movetoworkspace, 3
bind = SUPER, F4, movetoworkspace, 4
bind = SUPER, F5, movetoworkspace, 5
bind = SUPER, F6, movetoworkspace, 6
# ┌──────────────────────────────────────────────────────────────────────────────┐
# │ Rotación de Stack                                                            │
# └──────────────────────────────────────────────────────────────────────────────┘

# Rotar stack: la siguiente ventana de la pila pasa a ser maestra,
# manteniendo el foco en el lado derecho
bind = SUPER, c, layoutmsg, rollnext
#bind = SUPER, bar, layoutmsg, swapsplit
